hcloud_api_token: ENC[AES256_GCM,data:KYdnRXRvZEre0gygHTdSPpgwXQUVdwkIkaqHiOAHUcHR1Dgy/fGuBF6qdwRMrL2hS7r2f/SIF2P+LgMNj0lIcw==,iv:X7or49CnrWfeHC1uqlGjy47Y6vPHiTVJgCTWt4N4J4Y=,tag:ofAHglJvd50T8k4cFOcHSw==,type:str]
tf_cloud_token: ENC[AES256_GCM,data:uAEseUVXLYHId5X0nlKYSJn8k2O5S1jVwqyN/dXIFnKrnkBGk5gi0ysb8iupZac4MhXF43jLLT6AJslDAsMulmZ14ao00jUGACn3+R/hmcu9WSUX66K5cixT,iv:b2zKp/PPTek9eXhYX49DNmF29Tw6RMXpPfHvEy2Y9Ic=,tag:EYgBi+Gd7Cv+dh771xVqow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1le8tylvxq3haq7xz6k8l2re7pl52dfm0cyqad2usfh2el5w4qeesk4w7nh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdVVSdHkxTElMbWZLZFdE
            TVV1MldPSUY3SEpnWFhNUFg0V0gxN3hpc1hzCk44anB2L1RDSjBFMmFkQ2J5Z1Av
            R1REa0tDaVcyclJ0MzVlcU1uWGZXSHcKLS0tIEdNZXVPMU12Ymt0TzdOY0tvWWww
            YkdiU3pTZWVvY0p5WmdJMFBXbUx5TFkK4lIKKxZylQAGS0uIF6cPmFk/U3+gQJtj
            FgTDVjaMlZpR81KrjehFHMKaaoCiZg1PUZkeCFhDbUyDy4MqB/gghQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T19:48:34Z"
    mac: ENC[AES256_GCM,data:PU9+Ol2lBnZa1tukJTzGg6ZKLiTpPQvRHttE+OWybz6MqpabBmvMm/85MbVxpAYutHjJdfGLy+ZGa+Jjlx9wPuGyDdRmCf/80VaWFlJpU8TZwSQgCKLCL/wAXLOyza2oAzcfHHOOgin+RYakJGKfNb6tD89jl6WgFcKU0LcEQrU=,iv:Sbv//H1Qdoz4Pusvdu7ZpG53Ij4MvPMiGimo7knYXPs=,tag:XVANb83LLWNr+p+oe8+PCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
