hcloud_api_token: ENC[AES256_GCM,data:8LQomfRaLcy4nAkMJwMklVZYKd3nd7cjQ8ywKip8i7X8FHoecA+5UAIFMTierDCwK6qd65y5xQPDoTU30nEA7A==,iv:U4PZ+9zkBrX5HH17268JUyDv43YuZ6A70VGAjpn64ec=,tag:oY82qqjsuuEiIH7GB1JmUQ==,type:str]
tf_cloud_token: ENC[AES256_GCM,data:m4TkJu4sjxBnn83ajcN65v52Wc0M/HfdrcS91S1NEEPwqeKWaIQnA44ecsntJFkdTyBl0ZemGdD5DxYUsfyqPC5jM2bdN6SpiyR+n2Ja2lUSAjZnw3kYhHGD,iv:I8R1LvWBy4iYjbhBDOalvGr0GoAZX9sGahxzY9Ukq18=,tag:1ElOJm+vQxUjxS9n6ebsBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1le8tylvxq3haq7xz6k8l2re7pl52dfm0cyqad2usfh2el5w4qeesk4w7nh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4amJqNEV2ZXd4czJuVG9D
            TFpTa3VDZFdwZW5UZmhvemdyNWI3OEJRbm1rCjhaRkVYcEFsaGQvK2hUN1pUR2xs
            ckQ1Q09PZGVCUzZLcEwxZkVuM0gvMTQKLS0tIGw3dTZxeUgwV0NleW53Vk5SeWFX
            M0dxMndVaDIvOHpvUWluS0g0cW5ieTQKbs7GXn/y2suKGbGOyA8htLTGVs6QouCs
            k5Tj6joCXPPGxOj0HHQ6UYBQXVnq25QU43oMHZXBDlXvAY4RqT1ZOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T18:33:46Z"
    mac: ENC[AES256_GCM,data:oZlU6z6EpWq/I3gH9r+rbWfcd7YKSmAV2gkxF8UYZCABf/ZiPqRW+HiiqgornkDCGZRuncgB1lCqMtfueqZ+DJd4qetn7q8fwvuWBOrgNe7XVEm37OT3yRshQLv5cFqLm9rMNib6GYKCRDxKIqgsZt3XTvBl0ySUUEsrkiOseko=,iv:M0ys2Gy8dlHLj7EVlxRSHcMfqCwhEIy3cThhEGHaeUU=,tag:eNIz0C5ONVkrNgwf1yAsgg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
