hcloud_api_token: ENC[AES256_GCM,data:u42DzxF/YiV9vILFi2DmrcEL2mJB0MiNwsctVxvSJb+Z2JVNfmGQN+lecCJxvo2NxWOIk4jyqExVyLd37aEciw==,iv:tOBr1Ae7O7AXNfpwIRLHgIxyaix6OxyYZznnaKe5mis=,tag:RRAyt8tTfOd6zyJPUQM50g==,type:str]
tf_cloud_token: ENC[AES256_GCM,data:IU4+dx8K2vosQBw7sUyXVqsZB4EDnA0Ej38F/66dA5E62PlABXiiQzrrj4rwkdWMSe+M7/kkuzKKCQzKfHVGP+207lSzkbGWknFHdGqJooE/N+T2DQdrACHp,iv:FM2GTxU1gCLOTuE6VhBa7PC/nMQm3MWhw50argEsYEY=,tag:Y28kWjy7ROZW5AMqBE24/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1le8tylvxq3haq7xz6k8l2re7pl52dfm0cyqad2usfh2el5w4qeesk4w7nh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV24xRG1vT0NibUxSOHNB
            UDR3SnRCa3p0Z0RjU0JCWmd5emNLRmplQjJJCmJGdVAzLzA2NXgvbDVkVkUxOWNv
            UEFUbVN6MGdLNm8zWi9MNXdmSkN6czAKLS0tIFRKdjhxZm5OWkJwTytvZFg1Rldo
            THNxamRFQ2RITE4xSi8rODFoRzM5U1kKpMQf/D4njkdH3BSxZeGIXRfNDlvzZt3K
            8jHqJcJG/cRPI1fVBra/QMGcCVs0gbdaaRxZhfUt+RgaeQUMFyNlSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-10T08:51:29Z"
    mac: ENC[AES256_GCM,data:C9u7zdD47DOOALHFD9NwqBMWB8Aguf4qqYguhgaX2uampzB6+zOmjvbUwgIPFMxReYzj40XRGslhLpDj26oRO6Kxaah65avuhhm/DswFL/j7k4K0JkRoLXIfYVdIEwyzKZs7CFJf095vxSyLPsqCjVjVdAu4SOZMN01f4gIXJ9w=,iv:JvP6B38w4XhwL1Hn6E5lAddTuyle98WgDfKKY5O1Kro=,tag:PPfHSpVUilHGQDCgM1L6lQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
