# let's make anchors so we can use names to refer to the keys
keys:
  - &automation age1le8tylvxq3haq7xz6k8l2re7pl52dfm0cyqad2usfh2el5w4qeesk4w7nh

# actual sops config
creation_rules:
  - path_regex: (\.enc)?\.(yaml|json)$
    key_groups:
    - age:
      - *automation
