steps:

  validate:
    image: nixos/nix:2.19.2
    # when:
    #   event: pull_request
    commands:
      - NIX_CONFIG="experimental-features = nix-command flakes" nix run .#plan
    secrets: [ sops_age_key ]
