pipeline:

  validate:
    image: alpine:3.16
    # when:
    #   event: pull_request
    commands:
      - apk add --no-cache terraform
      - terraform version
      - |
          cat << EOF > terraform.rc
          credentials "app.terraform.io" {
            token = "$TERRAFORM_CLOUD_TOKEN"
          }
          EOF
      - terraform init
      - terraform validate
      - terraform plan -var ""
    secrets: [ terraform_cloud_token ]
